### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by Jnchi** [CyberNinjas/pam_aad#10]
[![Build Status](https://travis-ci.org/CyberNinjas/pam_aad.svg?branch=c-dev)](https://travis-ci.org/CyberNinjas/pam_aad)

_*Requires administrator privileges on the repository to enable._

[.travis.yml](https://github.com/CyberNinjas/pam_aad/blob/c-dev/.travis.yml)
```
language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:ben-collins/libjwt
  - sudo apt-get update

script: autoreconf --install && ./configure && make

sudo: false

addons:
  apt:
    packages:
        - libjwt-dev
        - libpam0g-dev
        - libssl-dev
```

[Travis CI - Building a C Project](https://docs.travis-ci.com/user/languages/c/)

Depends on: https://github.com/CyberNinjas/pam_aad/issues/11
